try:
    # TODO あとで削除する
    raise ValueError
except ValueError:
    print('Do something')
    raise   # 今キャッチしているエラーが何かを確認することができる。



